### ISSUE TITLE
On Solaris, The DATA constant succeeds in locking the file DATA came from FAILED

### ISSUE THREAD

**Issue by ngoto** [ruby/rubyspec#121]
moved from https://github.com/ruby/mspec/issues/12 and modified.

```
$ MSPECOPT="--verbose" make test-rubyspec
(snip)
/XXXXX/trunk-51741/spec/rubyspec/language/predefined/data_spec.rb                                           /XXXXX/trunk-51741/spec/rubyspec/language/predefined/fixtures/data_flock.rb:1:in `flock': Bad file number @ rb_file_flock - /XXXXX/trunk-51741/spec/rubyspec/language/predefined/fixtures/data_flock.rb (Errno::EBADF)
        from /XXXXX/trunk-51741/spec/rubyspec/language/predefined/fixtures/data_flock.rb:1:in `<main>'
F
(snip)

1)
The DATA constant succeeds in locking the file DATA came from FAILED
Expected ""
 to equal "0"

/XXXXX/trunk-51741/spec/rubyspec/language/predefined/data_spec.rb:31:in `block (3 levels) in <top (required)>'
/XXXXX/trunk-51741/spec/rubyspec/language/predefined/data_spec.rb:3:in `<top (required)>'
(snip)
```

On Solaris, write access is needed to lock a file.
This is well known difference of behavior between Solaris and Linux.
As far as I know, no official spec is defined for flock and the behavior of flock is platform specific.
DATA is opened by Ruby interpreter with read-only mode.
So, I think the spec should be skipped on Solaris.

References:
http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/291535
https://rails.lighthouseapp.com/projects/8994/tickets/6662-fileflock-cant-lock-read-only-file-for-exclusive-access

**Comment by eregon** [comment]
Yes, this sounds right, thank you for the fix and the analysis!
