### ISSUE TITLE
Detach repo from rubyspec/rubyspec

### ISSUE THREAD

**Issue by deivid-rodriguez** [ruby/rubyspec#146]
Hi!

Currently `ruby/rubyspec` doesn't show up in github searches because it's a forked repo. Instead, `rubyspec/rubyspec` shows up so some people might get the idea that the project is actually dead when it's not (specially twitter-less people like me :) ). Maybe it makes sense to detach the repo from `rubyspec/rubyspec` (and credit the original repo somewhere in the README instead, for example).

I did this with `pry-byebug` a while ago, because a user raised the issue (https://github.com/deivid-rodriguez/pry-byebug/issues/29). You have to request it to github support, as specified [here](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork), and maybe it's also a good idea to ask/inform the old mantainers.

Thanks for the hard work!

**Comment by eregon** [comment]
You are right, I need to clarify this on GitHub.

**Comment by eregon** [comment]
This is fixed as ruby/rubyspec is now the root repository! :tada: 
And it indeed appears first in github searches :smiley:

**Comment by elia** [comment]
:rocket:

**Comment by hsbt** [comment]
Great!

**Comment by hsbt** [comment]
@eregon Should we detach ruby/mspec too?

**Comment by eregon** [comment]
@hsbt mspec and the rubyspec website are already roots of their networks as well :wink:

**Comment by vais** [comment]
Long live RubySpec!

**Comment by hsbt** [comment]
@eregon oh. I confirmed to mspec is root repository at https://github.com/ruby/mspec. but ruby organization view shows still forked repository.

<img width="327" alt="screenshot 2015-12-15 09 41 45" src="https://cloud.githubusercontent.com/assets/12301/11798663/433e7adc-a310-11e5-893d-0f89e54ef059.png">

I think it's github's internal issue :octocat:

**Comment by eregon** [comment]
@hsbt It seems fixed now.
