### ISSUE TITLE
Unsure how to spec out literal hash string key encoding behavior

### ISSUE THREAD

**Issue by headius** [ruby/rubyspec#162]
For jruby/jruby#3405, a bug reporter noted behavioral issues in JRuby's handling of String keys to Hash instances.

The correct behaviors are listed below, with JRuby 9.0.4.0 behavior noted where it differs:

* MRI freezes *and* deduplicates literal String keys in literal Hashes. JRuby 9.0.4.0 deduplicates all String keys inserted into any Hash.
* Frozen string deduplication must not change the encoding of the deduplicated String. JRuby 9.0.4.0 is not checking encodings in the internal deduplication table.

I'm not sure how to specify these behaviors properly in RubySpec, given that the original test script provided in jruby/jruby#3405 expects the script's default encoding to be ASCII-8BIT and the strings entered into the test Hashes *must* be direct, literal keys. RubySpec files are typically UTF-8, and it would not be appropriate to modify e.g. language/hash_spec.rb to be ASCII-8BIT throughout.

I *do not* believe we should specify the deduplication effects, since they are not intended to be specified behavior in any Ruby. Any test we write should only be confirming that the various ways to enter String keys into Hash do not lose encoding information.

I wrote a spec based on the original code, but then realized it did not actually use literal strings in literal hashes where it should, and was not testing what we want to test. I've included it below as an example.

```ruby


  it "preserves original string keys' encodings after insertion" do
    ascii_str = 'hello'.force_encoding('ASCII-8BIT')

    str = ascii_str.dup
    hash1 = {ascii_str.dup => 1}
    hash2 = {str => 2}

    str.encoding.should == hash1.keys.first.encoding
    str.encoding.should == hash2.keys.first.encoding

    str = ascii_str.dup.force_encoding('UTF-8')
    hash1 = {'hello'.force_encoding('UTF-8') => 1}
    hash2 = {str => 2}

    str.encoding.should == hash1.keys.first.encoding
    str.encoding.should == hash2.keys.first.encoding

    str = ascii_str.dup.force_encoding('UTF-8')
    hash1 = {}
    hash1[str] = 1
    hash2 = {}
    hash2[str] = 2

    str.encoding.should == hash1.keys.first.encoding
    str.encoding.should == hash2.keys.first.encoding

    ascii_str2 = 'world'.force_encoding('ASCII-8BIT')

    str = ascii_str2.dup.force_encoding('UTF-8')
    hash1 = {ascii_str2.dup.force_encoding('UTF-8') => 1}
    hash2 = {str => 2}

    str.encoding.should == hash1.keys.first.encoding
    str.encoding.should == hash2.keys.first.encoding

    ascii_str3 = 'unused'.force_encoding('ASCII-8BIT')
    str = ascii_str3.dup
    hash1 = {ascii_str3.dup.force_encoding('UTF-8') => 1}
    hash2 = {str.force_encoding('UTF-8') => 2}

    str.encoding.should == hash1.keys.first.encoding
    str.encoding.should == hash2.keys.first.encoding
  end
```

**Comment by headius** [comment]
It also occurs to me the test script from jruby/jruby#3405 is not quite correct also; we should be confirming the encodings of literal String keys in literal Hashes for multiple encodings, which is not possible without having separate files with explicit encoding magic comments. Tricky, tricky...

**Comment by eregon** [comment]
Maybe we could have multiple fixtures files with different magic encodings, which we would `require`, and then add string literals to some shared Hash?

**Comment by eregon** [comment]
But indeed, a Hash literal with String literals of different encodings seems hard to produce.

**Comment by headius** [comment]
Yes, I suppose these would be fixtures, like fixtures/hash_with_ascii_keys.rb, fixtures/hash_with_utf8_keys.rb. I'll see if I can come up with something today.

**Comment by eregon** [comment]
I think specifying JRuby-like behavior (not only literal strings) would already be useful, so if the first spec spots the bug in JRuby, it's already a valuable addition.

For the literal-literal case, then indeed having a Hash literal with UTF8 literals in a file, and another file with Hash and keys of another encoding (but same bytes) should show the issue if there is global dedup table.

**Comment by headius** [comment]
The fixture approach worked out nicely. Spec is pretty simple and it does appear to show JRuby 9.0.4.0 failing and 9.0.5.0 working correctly.

**Comment by headius** [comment]
I'm going to opt to punt on any specs for global deduplication right now, since it is intended in Ruby 2.2+ (and probably 3.0, and definitely in Java's interned strings) to be a side effect you should not rely upon.

**Comment by eregon** [comment]
Awesome!
Yes, I would consider deduplication to be an impl-dependent optimization (at least before Ruby 3.0).
