### ISSUE TITLE
With 652d33279aa242623e09e671233832ace29f1f49, core/kernel/spawn_spec.rb stalls forever on Solaris

### ISSUE THREAD

**Issue by ngoto** [ruby/rubyspec#176]
After 652d33279aa242623e09e671233832ace29f1f49, core/kernel/spawn_spec.rb stalls forever on Solaris 10.
With 652d33279aa242623e09e671233832ace29f1f49, it seems that 'ruby -e "sleep"' is spawned, but this process apparently never ends, and the parent spec process waits the never-ending process forever. So, I think the change is wrong and I reverted the commit.

**Comment by ngoto** [comment]
4960e9804f77ebfcb253a67e41e943e208e27be5 reverts the commit 652d33279aa242623e09e671233832ace29f1f49

**Comment by eregon** [comment]
But this means that `read_nonblock` is actually blocking on Solaris, even if the other end of the pipe is closed?

**Comment by eregon** [comment]
These specs are quite confusing however :/, could be much easier to just `open()` and check the fd number.

**Comment by ngoto** [comment]
No, read_nonblock never blocks, and raised expected errors.
It blocks at "Process.wait(pid)".
During make test-rubyspec, RUBY_EXE is a wrapper script that invokes true ruby binary.
So, "Process.kill(:TERM, pid)" only kills the wrapper script and the execution of 'ruby -e "sleep"' invoked by the wrapper runs forever.

**Comment by eregon** [comment]
I see, thanks for investigating.
Maybe the wrapper should forward SIGTERM to the spawned ruby?

**Comment by ngoto** [comment]
It is not because of the wrapper script, but system's shell (normally /bin/sh).
Process.spawn(ruby_cmd("sleep")) runs ruby with the shell, and returns the pid of the shell process.
On Solaris, when sending SIGTERM to the shell process, it waits for the finish of the child ruby process, but never sends signals to the child ruby.

**Comment by eregon** [comment]
Ah, unfortunate indeed.
So I guess we should either make the Ruby process write its PID somewhere,
or make it so that just its exit status is enough to know success/failure.

**Comment by ngoto** [comment]
I think using signal is bad idea. The behavior of signals could be different depending on OS and shell.

**Comment by eregon** [comment]
Agreed, thanks for the fix!
