### ISSUE TITLE
IO#advise behavior on platforms that don't have it

### ISSUE THREAD

**Issue by chuckremes** [ruby/rubyspec#183]
This isn't necessarily a bug, but I think the behavior is incorrect. (If I should open this as a bug against MRI, let me know.)

On systems that do not support the `posix_fadvise` function, a call to IO#advise (with suitable args) returns nil/success. In other words, it silently fails without actually executing that OS function. However, I believe it should raise `NotImplementedError` on those platforms. That behavior seems more correct rather than silently failing.

I ran across this while running the kernel/core/io specs against the Rubinius ffi-io branch (I'm the principle author of that branch). A few months ago I modified the Rubinius specs with a feature guard `with_feature :posix_fadvise` so it would skip those specs on unsupported platforms.

What do you think?

**Comment by headius** [comment]
I'm not sure what the proper behavior is. Some methods in Ruby that are not implemented raise an exception (e.g. fork), and some return nil (e.g. several functions in the 'etc' extension just return nil on Windows).

`fadvise` might be a weird one to have fail hard, since it doesn't actually change any visible functionality. It's just hinting to the kernel how a program will use a given file, right? So having it raise an error might be rather intrusive.

How are you testing `fadvise` anyway?

**Comment by eregon** [comment]
It seems intended at least in 2.3: https://github.com/ruby/ruby/blob/v2_3_0/NEWS#L111-L112 and https://bugs.ruby-lang.org/issues/11806.

@chuckremes Which particular specs are you looking at?

**Comment by chuckremes** [comment]
@headius @eregon I'm referring to specs in the rubinius ffi-io branch (that I wrote). The current behavior where it failed silently seemed wrong to me, so I put a feature guard around it. Here's a pointer:

https://github.com/rubinius/rubinius/blob/ffi-io/spec/ruby/core/io/advise_spec.rb#L5

I raised the issue here because you guys are maintaining the "canonical" spec suite.

**Comment by chuckremes** [comment]
I see in the issue that it refers to its current behavior that it is acceptable to fail silently.

https://bugs.ruby-lang.org/issues/11806

I view the change in 2.3.0 to indicate that they are just building on the current behavior and not making any judgement as to whether or not the current behavior is correct.

**Comment by headius** [comment]
@chuckremes Why do you think it should raise an error if it's not implemented for a given platform? I mean...even on platforms where it's implemented, it's almost impossible to tell that it did anything. Your specs don't even test actual `fadvise` behavior...just peripheral behavior like error cases and accepted parameters.

**Comment by chuckremes** [comment]
@headius I think calls to `advise` should raise NotImplementedError on platforms that don't support that function because it is truthful. Yes, it's a hint and might be ignored, but that's a distraction from the issue. If the function doesn't exist, it should raise. 

Yes, I know the my current specs don't do that. I'm asking HERE if you all think that raising NotImplementedError should be the correct behavior. If you do, then I'll submit a PR and open a bug with MRI. If you do NOT, then I'll change my specs to match the accepted behavior.

**Comment by headius** [comment]
@chuckremes Ok, I agree with that. It should also be marked as "not implemented" so it doesn't show up in respond_to?, similar to how fork is marked.

I'd say file an issue and we'll see what the other ruby-core folks say.

**Comment by headius** [comment]
There is a middle option too...mark it as not implemented (for respond_to?) but allow it to be a no-op when called. Code that expects it to not raise an error will be ok, and code that queries it first will be ok.

**Comment by eregon** [comment]
Yes, definitely ask on the MRI bug tracker and maybe link with https://bugs.ruby-lang.org/issues/11806#note-6.

**Comment by chuckremes** [comment]
Opened on the redmine bug tracker here:  https://bugs.ruby-lang.org/issues/11973

**Comment by eregon** [comment]
I think we can close this and wait for resolution on redmine then.

---
About practical details, I think using RubySpec `features` is not best tool to use here, I would rather use platform guards if they are enough or some check like `has_posix_fadvise = some_io.respond_to? :advise` and have specs for both cases.
The set of features should be small and clear, otherwise it's too easy for implementations to not keep track of them in their config file.

**Comment by chuckremes** [comment]
Per the responses to the bug issue opened for MRI, this is a dead issue. I'll revise the Rubinius specs to conform.
https://bugs.ruby-lang.org/issues/11806

**Comment by eregon** [comment]
@chuckremes Thanks! I'll close the MRI issue then.
