### ISSUE TITLE
Is the migration to ruby/rubyspec complete?

### ISSUE THREAD

**Issue by eregon** [ruby/rubyspec#28]
@hsbt Is the migration to ruby/rubyspec complete?
It looks good to me!

**Comment by hsbt** [comment]
@eregon I create "rubyspec" team and added you into it team. Please start to migrate archive branch into ruby branch of this repository. ( I think it's better to rename ruby branch to master branch when migration is finished )

**Comment by eregon** [comment]
Thanks!
Agreed, a branch ruby/ruby is sort of confusing.
