### ISSUE TITLE
Dir#read test

### ISSUE THREAD

**Issue by nobu** [ruby/rubyspec#53]
`core/dir/read_spec.rb` just tests only one entry.
I think it should be tested that all results are included in the `Dir#entries` result, and it returns `nil` after all entries are read.

How can I write tests for this kind of sequence behavior in mspec?

**Comment by anthonycrumley** [comment]
There is a spec file for each method, so `Dir#entries` behavior is specified in `core/dir/entries_spec.rb`.  The following may cover the behavior of all results being included in the `Dir#entries` result.

https://github.com/ruby/rubyspec/blob/master/core/dir/entries_spec.rb#L17-L24

Seems that there should be a specification for `Dir#read` in `core/dir/read_spec.rb` for the behavior after all entries are read.  Something like...
```
it "returns nil after all entries are read" do
  # code to read all entries and assert nil is returned next.
end
```

**Comment by eregon** [comment]
Something like:
```ruby
dir = Dir.open DirSpecs.mock_dir
entries = []
while entry = dir.read
  entries << entry
end

# last entry
entry.should == nil

entries.sort.should == DirSpecs.expected_paths
```

**Comment by eregon** [comment]
It might be worth splitting to specify
`it "returns nil when there are no more entries"` and
`it "returns each entry successively"`
separately for clarity. But this seems a bit nitpicking.
