### ISSUE TITLE
Maintaining RubySpec for 2.0

### ISSUE THREAD

**Issue by eregon** [ruby/rubyspec#55]
Maintaining RubySpec for ruby 2.0.0 releases tends be a much bigger challenge than >= 2.1 versions.

Failures often happen on Travis for hard-to-track reasons (https://travis-ci.org/ruby/rubyspec/jobs/54859872 for instance). I am not sure how we can fix these. @nobu, any idea? :smile: 
Locally I have 11 failures + 2 errors with 2.0.0p643 which also seem non obvious to fix (badly-encoded strings, EBADF, etc).

Does RubyCI runs the new RubySpec for 2.0 as well?

**Comment by eregon** [comment]
An example of 12 failures + 2 errors, similar to what I have locally:
https://travis-ci.org/ruby/rubyspec/jobs/54864322

**Comment by anthonycrumley** [comment]
This is sorta related.  Some behavior seems to have not been considered in one version and then consideration for it is added in a later version.  An example is TypeError in SizedQueue#new.
```
2.2.0 :001 > SizedQueue.new(Object.new)
TypeError: no implicit conversion of Object into Integer
	from (irb):1:in `initialize'
	from (irb):1:in `new'
	from (irb):1
	from /Users/anthonycrumley/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
2.2.0 :001 > SizedQueue.new("foo")
TypeError: no implicit conversion of String into Integer
	from (irb):1:in `initialize'
	from (irb):1:in `new'
	from (irb):1
	from /Users/anthonycrumley/.rvm/rubies/ruby-2.2.0/bin/irb:11:in `<main>'
```
```
2.0.0-p598 :001 > SizedQueue.new(Object.new)
NoMethodError: undefined method `>' for #<Object:0x007fe8ea142d48>
	from /Users/anthonycrumley/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/thread.rb:264:in `initialize'
	from (irb):1:in `new'
	from (irb):1
	from /Users/anthonycrumley/.rvm/rubies/ruby-2.0.0-p598/bin/irb:12:in `<main>'
2.0.0-p598 :002 > SizedQueue.new("foo")
ArgumentError: comparison of String with 0 failed
	from /Users/anthonycrumley/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/thread.rb:264:in `>'
	from /Users/anthonycrumley/.rvm/rubies/ruby-2.0.0-p598/lib/ruby/2.0.0/thread.rb:264:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /Users/anthonycrumley/.rvm/rubies/ruby-2.0.0-p598/bin/irb:12:in `<main>'
```
Should we specify the behavior of 2.0 in this case or just specify the purposeful behavior of 2.1+?  It seems that 2.0 did not explicitly handle non-numeric arguments so the NoMethodError and ArgumentError are just accidental failures that might not need be specified.

I am still torn over what to do with behavior like this.

**Comment by eregon** [comment]
In general, it is always best to describe all maintained versions.
In the case of 2.0 areas like keywords arguments, I tend to feel it is worth an exception since in many cases the behavior was just not defined.
In this particular situation, I think it is fair enough to not specify 2.0 behavior since it does not bring much and it would be fairly hard to express the intention. However, specifying it documents the change of behavior, which might be nice to have.

**Comment by eregon** [comment]
Specifying the latest stable version is what matters to most users of RubySpec, so I would think spending considerable time on specifying exceptions of older stable versions is probably not worth it.

**Comment by eregon** [comment]
It seems all these failures are due to some bad interaction between the SpinnerFormatter and ARGF/IO specs. Using the dotted formatter "magically" fixed the build:
https://travis-ci.org/ruby/rubyspec/builds/58433618
