### ISSUE TITLE
Having a separate branch for Ruby 2.0.0 ?

### ISSUE THREAD

**Issue by eregon** [ruby/rubyspec#72]
I am thinking to have a separate branch for ruby 2.0.0 as it behaves quite differently from newer versions.
Getting the build stable is almost impossible as it fails with [EBADF](https://travis-ci.org/ruby/rubyspec/jobs/65571824) or what looks like [encoding confusion](http://rubyci.blob.core.windows.net/arch/ruby-2.0.0/log/20150606T101112Z.fail.html.gz).
Maintaining proper guards for 2.0 is also not trivial.
The branch would not be updated with new specs but only receive occasional fixes if it can help the CI.
For the current head of the branch I am thinking to e0769b633c38e0738b38db2bb2a33df0e9323375 as it seems rather stable on Linux+OS X on Travis at that time and for a few commits after (and backport caf25d4880315002d90bc31b4b717fce0b447dac).

@hsbt @nurse what do you think?
P.S.: It seems even the bundled test-all tends to fail sporadically on http://rubyci.org/.

**Comment by nurse** [comment]
As far as I understand, EBADF is caused because someone closed the fd in object finalization. It happens by for example IO.for_fd with autoclose. Therefore it happens accidentally on 2.0.0 now, but it may disappear and appear on another branch with adding or removing specs.
Encodings issues seems because locale difference. It can be fixed with setting locale or default_external or soemthing.
Anyway I don't object dropping support for 2.0.0.

**Comment by akr** [comment]
RubySpec on Ruby 2.3 still fails with EBADF such as:
http://www.rubyist.net/~akr/chkbuild/debian/ruby-trunk/log/20150514T200400Z.log.html.gz

test-all uses test/lib/leakchecker.rb to detect several kind of leaks including possible EBADF.
It may be considerable to implement similar mechanism in RubySpec.

**Comment by eregon** [comment]
@akr Thanks, I will try integrating it into MSpec, early results seem very useful.

The ARGF specs seem rather tricky. It seems MRI mostly spawns a new Ruby to "reset" ARGF and not leak open files. Spawning sub-rubies is however rather expensive, especially on alternate implementations.
I am thinking to use `ARGF.class.new` so the original ARGF is left untouched and if we only have two files as input, it's not too hard to close them afterwards.

**Comment by eregon** [comment]
It looks like 2.0.0 on Travis and RubyCI only has 1 or 2 errors/failures after my efforts to track down most fd leak, yet there there is still one EBADF on some builds of 2.0.0. I am not sure where it comes from, but I would guess some well hidden usage of `IO.for_fd`/`IO.new`.

**Comment by eregon** [comment]
It would seem that 69e6d7184cdbbcbf3ed5a68fc2b065d9f3e4c71a actually removed the last source of EBADF on 2.0.0.
I tracked it down with `GC.stress = true` while running IO specs.

So, let's keep 2.0.0 in master.
