### ISSUE TITLE
Add Array#bsearch_index specs

### ISSUE THREAD

**Issue by hsbt** [ruby/rubyspec#76]
we added new method named "Array#bsearch_index"

see https://github.com/ruby/ruby/commit/c64d283f9aa01388ebfd2d9d30b0f0a306f25d27

**Comment by JuanitoFatas** [comment]
I'll work on it :smile:

**Comment by eregon** [comment]
@JuanitoFatas Thanks :+1: 
Maybe it can somehow be shared with `Array#bsearch`.

**Comment by eregon** [comment]
Fixed by @JuanitoFatas!

**Comment by hsbt** [comment]
@JuanitoFatas Thanks!
